---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaskapp-8277127070-release
  namespace: personal-rnd
spec:
  releaseName: flaskapp-8277127070-t1
  targetNamespace: personal-rnd
  interval: 24h
  chart:
    spec:
      chart: base-deployment
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: crazedencoder
        namespace: flux-system
      interval: 24h
  values:
    global:
      applicationName: flaskapp-8277127070-t1
    replicaCount: 1
    image: registry.crazedencoder.com/8277127070/sample-app:v2
    containerDetails:
      pullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
          name: pw-address
    service:
      type: ClusterIP
      port: 3021
      targetPort: pw-address

    resources:
       limits:
         cpu: 100m
         memory: 100Mi
       requests:
         cpu: 80m
         memory: 80Mi

---
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: flaskapp-8277127070-t1
    namespace: personal-rnd
spec:
    scaleTargetRef:
        deployment: flaskapp-8277127070-t1-release
        service: service-flaskapp-8277127070-t1
        port: 3021
    replicas:
      min: 2
      max: 5

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: letsencrypt-ingress-8277127070-flaskapp
 namespace: personal-rnd
 annotations:
  nginx.ingress.kubernetes.io/ssl-redirect: "true"
  nginx.ingress.kubernetes.io/secure-backends: "false"
  nginx.ingress.kubernetes.io/enable-access-log: "false"
  cert-manager.io/cluster-issuer: letsencrypt-issuer
  nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  kubernetes.io/ingress.class: nginx
spec:
 tls:
 - hosts:
   - 8277127070t1.crazedencoder.com
   secretName: letsencrypt-issuer
 rules:
 - host: 8277127070t1.crazedencoder.com
   http:
     paths:
     - pathType: Prefix
       path: /
       backend:
         service:
           name: service-flaskapp-8277127070-t1
           port:
             number: 3021