---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda-release
  namespace: personal-rnd
spec:
  releaseName: keda
  targetNamespace: personal-rnd
  interval: 24h
  chart:
    spec:
      chart: keda
      version: 2.9.1
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
      interval: 24h
  values:
    

    resources:
      limits:
        cpu: 300m
        memory: 300Mi
      requests:
        cpu: 300m
        memory: 300Mi


# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: keda-add-ons-http-release
#   namespace: personal-rnd
# spec:
#   releaseName: keda-add-ons-http
#   targetNamespace: personal-rnd
#   interval: 24h
#   chart:
#     spec:
#       chart: keda-add-ons-http
#       version: 0.2.2
#       sourceRef:
#         kind: HelmRepository
#         name: kedacore
#         namespace: flux-system
#       interval: 24h
#   values:
#     resources:
#       limits:
#         cpu: 300m
#         memory: 300Mi
#       requests:
#         cpu: 300m
#         memory: 300Mi