
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: letsencrypt-ingress-916416520-flaskapp
 namespace: personal-rnd
 annotations:
  nginx.ingress.kubernetes.io/ssl-redirect: "true"
  nginx.ingress.kubernetes.io/secure-backends: "false"
  nginx.ingress.kubernetes.io/enable-access-log: "false"
  cert-manager.io/cluster-issuer: letsencrypt-issuer
  nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  kubernetes.io/ingress.class: nginx
spec:
 tls:
 - hosts:
   - 916416520.crazedencoder.com
   secretName: letsencrypt-issuer
 rules:
 - host: 916416520.crazedencoder.com
   http:
     paths:
     - pathType: Prefix
       path: /
       backend:
         service:
           name: service-flaskapp-916416520
           port:
             number: 98721 # NOTE: if this number is already used by someone , your application wont run. To avoid this, use your employee ID, For Example 3132
