---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-release
  namespace: personal-rnd
spec:
  releaseName: rabbitmq
  targetNamespace: personal-rnd
  interval: 24h
  chart:
    spec:
      chart: rabbitmq
      version: 3.11.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 24h
  values:
    auth.username: admin
    auth.password: admin
    resources:
      limits:
        cpu: 300m
        memory: 300Mi
      requests:
        cpu: 300m
        memory: 300Mi