# replace the <mobilenumber> with your mobile number

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaskapp-8953259137-release
  namespace: personal-rnd
spec:
  releaseName: flaskapp-8953259137
  targetNamespace: personal-rnd
  interval: 24h
  chart:
    spec:
      chart: base-deployment
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: crazedencoder
        namespace: flux-system
      interval: 24h
  values:
    global:
      applicationName: flaskapp-8953259137
    replicaCount: 2
    image: registry.crazedencoder.com/8953259137/sample-app:v1
    containerDetails:
      pullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
          name: pw-address
    service:
      type: ClusterIP
      port: 3785 # NOTE: if this number is already used by someone , your application wont run. To avoid this, use your employee ID, For Example 3132
      targetPort: pw-address

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: letsencrypt-ingress-8953259137-flaskapp
 namespace: personal-rnd
 annotations:
  nginx.ingress.kubernetes.io/ssl-redirect: "true"
  nginx.ingress.kubernetes.io/secure-backends: "false"
  nginx.ingress.kubernetes.io/enable-access-log: "false"
  cert-manager.io/cluster-issuer: letsencrypt-issuer
  nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  kubernetes.io/ingress.class: nginx
spec:
 tls:
 - hosts:
   - 8953259137.crazedencoder.com
   secretName: letsencrypt-issuer
 rules:
 - host: 8953259137.crazedencoder.com
   http:
     paths:
     - pathType: Prefix
       path: /
       backend:
         service:
           name: service-flaskapp-8953259137
           port:
             number: 3785 # NOTE: if this number is already used by someone , your application 