---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: personal-rnd
spec:
  releaseName: kafka-release
  targetNamespace: personal-rnd
  interval: 24h
  chart:
    spec:
      chart: kafka
      version: 22.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 24h
  
  values:
    volumePermissions:
      enabled: true
    persistence:
      enabled: false
      size: 10Gi
    externalAccess:
      enabled: true
      service:
        type: NodePort
        ports:
          external: 9094
      autoDiscovery:
        enabled: true
    rbac:
      create: true