---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda-release
  namespace: personal-rnd
spec:
  releaseName: keda
  targetNamespace: personal-rnd
  interval: 24h
  chart:
    spec:
      chart: kafka
      version: 22.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 24h
  
  values:
    persistence:
      size: 20Gi