---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-release-v1
  namespace: personal-rnd
spec:
  releaseName: kafka1
  targetNamespace: personal-rnd
  interval: 24h
  chart:
    spec:
      chart: kafka
      version: 22.0.
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 24h
  
  values:
    persistence:
      enabled: false
    # service:
    #   type: NodePort
    externalAccess.enabled: true
    externalAccess.service.type: NodePort
    externalAccess.service.externalIPs[0]: '10.20.1.2'
    # externalAccess.autoDiscovery.enabled: true