---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-release
  namespace: personal-rnd
spec:
  releaseName: kafka
  targetNamespace: personal-rnd
  interval: 24h
  chart:
    spec:
      chart: kafka
      version: 22.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 24h
  
  values:
    persistence:
      enabled: false
    externalAccess:
      enabled: true
      service:
        type: NodePort
        ports:
          external: 9094
      autoDiscovery:
        enabled:  true
